version: '3.6'

services:
  wp:
    image: wordpress:latest
    ports:
      - 8083:80
    volumes:
      - type: bind
        source: /home/wordpress-data
        target: /var/www/html
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      - db
    links:
      - db

  wpcli:
    image: wordpress:cli
    volumes:
      - type: bind
        source: /home/wordpress-data
        target: /var/www/html
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      - db
      - wp

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      UPLOAD_LIMIT: 50M
    ports:
      - 8082:80
    links:
      - db

  db:
    image: mysql:latest
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - type: bind
        source: /home/wordpress-data
        target: /var/lib/mysql
      - ./wp-data:/docker-entry