---
# -- DOCKER INSTALL --
- name: Install and deploy Docker
  hosts: backends
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: true
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bullseye stable
        state: present
    - name: Update apt and install docker-compose
      apt:
        pkg:
          - docker-ce
          - docker-compose
          - docker-compose-plugin
        state: latest
        update_cache: true
    - name: Deploy ifconfig files
      copy:
        src: /home/eductive09/Linux_Project/ansible/ifconfig.io/
        dest: /tmp/ifconfig.io/
    - name: Deploy docker-compose template
      template:
        src: /home/eductive09/Linux_Project/ansible/templates/docker-compose.j2
        dest: /tmp/ifconfig.io/docker-compose.yml
    - name: Deploy Docker Compose stack
      community.docker.docker_compose:
        project_src: /tmp/ifconfig.io
        files:
          - docker-compose.yml