---
front:
  hosts:
    57.128.65.18:
      ansible_user: debian
      ansible_become: True

backends:
  hosts:
    57.128.69.202:
      ansible_user: debian
      ansible_become: True
    57.128.80.61:
      ansible_user: debian
      ansible_become: True

backend_sbg:
  hosts:
    57.128.69.202:
      ansible_user: debian
      ansible_become: True

backend_gra:
  hosts:
    57.128.80.61:
      ansible_user: debian
      ansible_become: True
