---
front:
  hosts:
    57.128.84.166:
      ansible_user: debian
      ansible_become: True

backends:
  hosts:
    51.91.151.226:
      ansible_user: debian
      ansible_become: True
    57.128.85.149:
      ansible_user: debian
      ansible_become: True

backend_sbg:
  hosts:
    51.91.151.226:
      ansible_user: debian
      ansible_become: True

backend_gra:
  hosts:
    57.128.85.149:
      ansible_user: debian
      ansible_become: True
