---
# -- NGINX INSTALL --
- name: Install and configure a kitten web page
  hosts: backends
  vars:
    the_best: "Mon user eductive09 : le meilleur !"
  tasks:
    - name: Ensure package nginx is installed
      apt:
        name: nginx
        state: latest
    - name: Ensure service nginx is running
      service:
        name: nginx
        state: started
    - name: Upload Kitten webpage
      template:
        src: /home/eductive09/Linux_Project/ansible/templates/index.j2
        dest: /var/www/html/index.html
    - name: Configure Nginx to listen on vrack
      template:
        src: /home/eductive09/Linux_Project/ansible/templates/default.j2
        dest: /etc/nginx/sites-available/default
      notify:
        - Restart nginx
  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

# -- HAPROXY INSTALL --
- name: Install and haproxy on front
  hosts: front
  tasks:
    - name: Ensure package haproxy is installed
      apt:
        name: haproxy
        state: latest
    - name: Ensure service haproxy is running
      service:
        name: haproxy
        state: started
    - name: Configure haproxy
      template:
        src: /home/eductive09/Linux_Project/ansible/templates/haproxy.j2
        dest: /etc/haproxy/haproxy.cfg
      notify:
        - Reload haproxy
  handlers:
    - name: Reload haproxy
      ansible.builtin.service:
        name: haproxy
        state: reloaded

# -- NFS PLAYBOOK START
- name: User NFS playbook
  import_playbook: '/home/eductive09/Linux_Project/ansible/nfs_config.yml'

# -- DOCKER PLAYBOOK START
- name: Use Docker playbook
  import_playbook: '/home/eductive09/Linux_Project/ansible/docker_config.yml'

# -- IPTABLE PLAYBOOK START
#- name: Use IPTable playbook
#  import_playbook: '/home/eductive09/Linux_Project/ansible/iptable_config.yml'
